### ISSUE TITLE
Milestone 1

### ISSUE THREAD

**Issue by propagated** [propagated/HyveLog#1]
- [x] Logging to the console.
- [x] Logging to a text file.

- [x] Determining if the caller is a console or service and logging appropriately.
- [x] Giving the user the choice (can be both) of where to log
